# Macro file for JZCaPA beam test 2018
# 
# To be run preferably in batch, without graphics:
# 
# 150 GeV NEUTRON

# Initialize kernel
/run/initialize


/control/verbose 0
/run/verbose 0
/tracking/verbose 0
/run/particle/verbose 0


#/gps/particle ion
#/gps/ion 82 208 0 0.0
#/gps/energy 31.2 TeV

# using alphas is useful if you would like to visualize the tracks (Pb ions require much more computing time)
#/gps/particle ion
#/gps/ion 2 4 0 0.0
#/gps/energy 600 GeV

#/gps/particle proton
/gps/particle neutron

# the beam energy is in gaussian profile
/gps/ene/mono 10 MeV


# General particle source  
/gps/pos/type Beam
/gps/pos/shape Circle
/gps/pos/centre 0 11 0  cm
/gps/direction  0 -1 0

#

#
#
# the beam is travelling along the z-axis 
 
#

#if using these commands in interactive mode to visualize, use this to allow more events to be displayed (do not use in batch mode)
#/vis/ogl/set/displayListLimit 1000000

#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add opticalphoton
#/vis/filtering/trajectories/particleFilter-0/add e-

##############################################################
##############################################################
# number of events
/run/beamOn 10
